### ISSUE TITLE
Steps to follow

### ISSUE THREAD

**Issue by msaad1311** [yingtaoluo/PDE-Discovery-with-Evolutionary-Tree-Search#1]
Hello, I came across your repo while searching for data driven discovery of PDEs and I must say I am really impressed by the work you have done. Is it possible that you can suggest the steps one needs to follow to implement your code on any other dataset?

Also can you share the code for the nonparametric sparse regression that you have mentioned in the README of the repo?

**Comment by yingtaoluo** [comment]
Our work is under review in a journal. We cannot give out too much
information now. This repo is just for supplementary materials for the time
being.

**Comment by yingtaoluo** [comment]
Thanks for your interest. If our paper is accepted, which will be in three months at most, we will release the full info. Now, this repo only contains at most 40% codes to implement our paper.

**Comment by msaad1311** [comment]
Hello, thanks for your response. I totally understand your point of view and I await for your journal result. I am sure it will definitely be accepted considering the novelty associated with your work. Just out of curiosity, can you kindly suggest in which journal have you submitted the paper?

**Comment by yingtaoluo** [comment]
Yeah, sure. I suggest we chat via Gmail.

**Comment by msaad1311** [comment]
Sure, can I have your gmail id in that case?

**Comment by yingtaoluo** [comment]
Hi, I have updated the repo description and added arxiv link of the paper.

**Comment by yingtaoluo** [comment]
Our paper is published and links are provided. Thanks.
